### ISSUE TITLE
Support for changing ordinals of a target injection point?

### ISSUE THREAD

**Issue by EthanRStokes** [Sinytra/Adapter#1]
would allow for an easy solution for Sinytra/Connector#40

**Comment by Su5eD** [comment]
Superseded by [DynamicInjectorOrdinalPatch](https://github.com/Sinytra/Adapter/blob/c3233f4a5ef4db81473d83f77cfd55dbb9180f4a/definition/src/main/java/org/sinytra/adapter/patch/transformer/dynamic/DynamicInjectorOrdinalPatch.java)
